knpu_oauth2_client:
    clients:
        # Configuration du client Google
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
            # Forcer l'utilisation de HTTPS pour la redirection
            # use_https: true