version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: matchroom_traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=matchroom.contact@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik/traefik.yml:/traefik.yml:ro"
      - "./docker/traefik/acme.json:/letsencrypt/acme.json"
    networks:
      - front

  # Caddy est déjà présent dans le projet Dunglas
  caddy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony.rule=Host(`matchroom.shop`,`www.matchroom.shop`)"
      - "traefik.http.routers.symfony.entrypoints=websecure"
      - "traefik.http.routers.symfony.tls.certresolver=le"
    networks:
      - front
      - default
    # On supprime les ports exposés 80/443 ici (Traefik les gère)
    expose:
      - "80"

networks:
  front:
    external: false
