api:
  dashboard: true
  insecure: false # Désactivé en production

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: matchroom.contact@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
